on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
    - name: install rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: install yt-dtl
      run: sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && sudo chmod a+rx /usr/local/bin/yt-dlp
    - name: export rclone.conf
      run: 'echo "$RCLONE_CONF" | base64 -d > ~/.rclone.conf'
      shell: bash
      env:
        RCLONE_CONF: ${{secrets.RCLONE_CONF}}
    - name: make
      run: make
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/rdl-linux
    timeout-minutes: 10