on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
    - name: install rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: export rclone.conf
      run: echo "$RCLONE_CONF" > ~/.rclone.conf
      env:
        SSH_KEY: ${{secrets.RCLONE_CONF}}
    - name: make
      run: make && ./bin/rdl-linux torrent test/cosmos-laundromat.torrent gdrive6:/
    timeout-minutes: 10